#!/bin/sh

start() {
	start-stop-daemon -b -m -S -p "/var/run/nanomq" -x "/bin/nanomq" -- start
}

stop() {
	start-stop-daemon -K -p "/var/run/nanomq"
}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage $0 {start|stop|restart}"
		;;
esac

